---
title: "1 - Introducción a Polars"
toc: true
---

[Polars](https://pola.rs/) es una librería de Python orientada a la **manipulación y análisis de datos tabulares**. 
Su API está pensada para trabajar de manera clara y eficiente con tablas, selecciones, filtros, agregaciones y transformaciones de columnas.

Las dos estructuras más importantes son:

* `DataFrame`: una tabla bidimensional con filas y columnas.
* `Series`: una estructura unidimensional que representa una columna de la tabla.

In [1]:
import polars as pl

import pyprojroot

ROOT = pyprojroot.here()

A lo largo de este apunte vamos a trabajar con datos de los juegos olímpicos que se encuentran en `olympics.csv`.
Este conjunto de datos, que contiene datos básicos de los atletas que participaron en los juegos olímpicos entre Atenas 1896 y Río 2016, fue publicado en la semana 32 del año 2024 proyecto TidyTuesday y contiene las siguientes variables:

| Columna  | Descripción                                                              |
|----------|--------------------------------------------------------------------------|
| `id`     | Identificador del atleta.                                                |
| `name`   | Nombre del atleta.                                                       |
| `sex`    | Sexo del atleta.                                                         |
| `age`    | Edad del atleta.                                                         |
| `height` | Altura del atleta en centímetros.                                        |
| `weight` | Peso del atleta en kilogramos.                                           |
| `team`   | País o equipo por el que compite.                                        |
| `noc`    | Código NOC asociado a la región o delegación.                            |
| `games`  | Nombre de la edición de los Juegos Olímpicos.                            |
| `year`   | Año de los Juegos Olímpicos.                                             |
| `season` | Temporada de los Juegos: invierno o verano.                              |
| `city`   | Ciudad anfitriona de los Juegos Olímpicos.                               |
| `sport`  | Deporte.                                                                 |
| `event`  | Prueba o evento específico.                                              |
| `medal`  | Medalla obtenida: oro, plata, bronce o valor faltante si no obtuvo medalla. |

## Lectura de datos tabulares

La lectura de datos es una de las tareas fundamentales en el análisis de datos. En Polars, muchas fuciones para importar datos comienzan con `read_` y devuelven un `DataFrame`.
Algunos ejemplos son:

* `pl.read_csv()`
* `pl.read_parquet()`
* `pl.read_excel()`
* `pl.read_json()`
* `pl.read_database()`

Los archivos CSV (valores separados por comas) son uno de los formatos más comunes para almacenar datos tabulares. En este caso, los datos están en `olympics.csv`. Vamos a usar `pl.read_csv()` para leerlos.

In [2]:
datos = pl.read_csv(ROOT / "datos" / "olympics.csv")

## Inspección de datos tabulares

La representación de un `DataFrame` en una Jupyter Notebook permite echar un primer vistazo a los datos:

In [3]:
datos

shape: (271_116, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 1      ┆ A Dijiang ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketba ┆ Basketba ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ ll       ┆ ll Men's ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Extra-Li ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ghtweigh ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ t        ┆       │
│ 3      ┆ Gunnar    ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football ┆ Football ┆ null  │
│        ┆ Nielsen   ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ Aaby      ┆     ┆     ┆   ┆           ┆          ┆ Football ┆       │
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold  │
│        ┆ Lindenau  ┆     ┆     ┆   ┆           ┆ ar       ┆ ar Men's ┆       │
│        ┆ Aabye     ┆     ┆     ┆   ┆           ┆          ┆ Tug-Of-W ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ar       ┆       │
│ 5      ┆ Christine ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆           ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 500      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135569 ┆ Andrzej   ┆ M   ┆ 29  ┆ … ┆ Innsbruck ┆ Luge     ┆ Luge     ┆ null  │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Mixed    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ (Men)'s  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Doubles  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 30  ┆ … ┆ Nagano    ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 34  ┆ … ┆ Salt Lake ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆ City      ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

No solo es posible ver las primeras y últimas filas de la tabla, sino que también es posible ver la cantidad de filas y columnas (`shape: (271_116, 15)`) y el tipo de datos de cada una de las variables. Con el objetivo de hacer un uso eficiente del almacenamiento y poder de procesamiento disponible, Polars ofrece una gran variedad de tipos de datos. A lo largo del curso los iremos conociendo.

In [4]:
type(datos)

polars.dataframe.frame.DataFrame

Si quisieramos ver solamente las primeras filas o columnas, podemos utilizar los métodos `.head()` y `.tail()` de `DataFrame`. Estos cuentan con un parámetro opcional `n` que permite controlar la cantidad de filas obtenidas.

In [5]:
datos.head()

shape: (5, 15)
┌─────┬────────────┬─────┬─────┬───┬───────────┬───────────┬───────────┬───────┐
│ id  ┆ name       ┆ sex ┆ age ┆ … ┆ city      ┆ sport     ┆ event     ┆ medal │
│ --- ┆ ---        ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---   │
│ i64 ┆ str        ┆ str ┆ i64 ┆   ┆ str       ┆ str       ┆ str       ┆ str   │
╞═════╪════════════╪═════╪═════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 1   ┆ A Dijiang  ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketbal ┆ Basketbal ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆ l         ┆ l Men's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Basketbal ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ l         ┆       │
│ 2   ┆ A Lamusi   ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo      ┆ Judo      ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Men's Ext ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ ra-Lightw ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ eight     ┆       │
│ 3   ┆ Gunnar     ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football  ┆ Football  ┆ null  │
│     ┆ Nielsen    ┆     ┆     ┆   ┆           ┆           ┆ Men's     ┆       │
│     ┆ Aaby       ┆     ┆     ┆   ┆           ┆           ┆ Football  ┆       │
│ 4   ┆ Edgar      ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-Wa ┆ Tug-Of-Wa ┆ Gold  │
│     ┆ Lindenau   ┆     ┆     ┆   ┆           ┆ r         ┆ r Men's   ┆       │
│     ┆ Aabye      ┆     ┆     ┆   ┆           ┆           ┆ Tug-Of-Wa ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ r         ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
└─────┴────────────┴─────┴─────┴───┴───────────┴───────────┴───────────┴───────┘

In [6]:
datos.tail()

shape: (5, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 135569 ┆ Andrzej   ┆ M   ┆ 29  ┆ … ┆ Innsbruck ┆ Luge     ┆ Luge     ┆ null  │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Mixed    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ (Men)'s  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Doubles  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 30  ┆ … ┆ Nagano    ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 34  ┆ … ┆ Salt Lake ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆ City      ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

In [7]:
datos.head(9)

shape: (9, 15)
┌─────┬────────────┬─────┬─────┬───┬───────────┬───────────┬───────────┬───────┐
│ id  ┆ name       ┆ sex ┆ age ┆ … ┆ city      ┆ sport     ┆ event     ┆ medal │
│ --- ┆ ---        ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---   │
│ i64 ┆ str        ┆ str ┆ i64 ┆   ┆ str       ┆ str       ┆ str       ┆ str   │
╞═════╪════════════╪═════╪═════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 1   ┆ A Dijiang  ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketbal ┆ Basketbal ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆ l         ┆ l Men's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Basketbal ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ l         ┆       │
│ 2   ┆ A Lamusi   ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo      ┆ Judo      ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Men's Ext ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ ra-Lightw ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ eight     ┆       │
│ 3   ┆ Gunnar     ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football  ┆ Football  ┆ null  │
│     ┆ Nielsen    ┆     ┆     ┆   ┆           ┆           ┆ Men's     ┆       │
│     ┆ Aaby       ┆     ┆     ┆   ┆           ┆           ┆ Football  ┆       │
│ 4   ┆ Edgar      ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-Wa ┆ Tug-Of-Wa ┆ Gold  │
│     ┆ Lindenau   ┆     ┆     ┆   ┆           ┆ r         ┆ r Men's   ┆       │
│     ┆ Aabye      ┆     ┆     ┆   ┆           ┆           ┆ Tug-Of-Wa ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ r         ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 1,000 me… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ le        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ le        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 1,000 me… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 27  ┆ … ┆ Lillehamm ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ er        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
└─────┴────────────┴─────┴─────┴───┴───────────┴───────────┴───────────┴───────┘

Para inspeccionar la estructura del `DataFrame` de manera programática se puede consultar su esquema (`schema`), los tipos de datos (`dtypes`) o la la cantidad de filas y columnas (`shape`).

In [8]:
datos.schema

Schema([('id', Int64),
        ('name', String),
        ('sex', String),
        ('age', Int64),
        ('height', Int64),
        ('weight', Float64),
        ('team', String),
        ('noc', String),
        ('games', String),
        ('year', Int64),
        ('season', String),
        ('city', String),
        ('sport', String),
        ('event', String),
        ('medal', String)])

In [9]:
datos.dtypes

[Int64,
 String,
 String,
 Int64,
 Int64,
 Float64,
 String,
 String,
 String,
 Int64,
 String,
 String,
 String,
 String,
 String]

In [10]:
datos.shape

(271116, 15)

También es posible obtener una tabla con el conteo de valores nulos por columna usando el método `null_count`.

In [11]:
datos.null_count()

shape: (1, 15)
┌─────┬──────┬─────┬──────┬───┬──────┬───────┬───────┬────────┐
│ id  ┆ name ┆ sex ┆ age  ┆ … ┆ city ┆ sport ┆ event ┆ medal  │
│ --- ┆ ---  ┆ --- ┆ ---  ┆   ┆ ---  ┆ ---   ┆ ---   ┆ ---    │
│ u32 ┆ u32  ┆ u32 ┆ u32  ┆   ┆ u32  ┆ u32   ┆ u32   ┆ u32    │
╞═════╪══════╪═════╪══════╪═══╪══════╪═══════╪═══════╪════════╡
│ 0   ┆ 0    ┆ 0   ┆ 9474 ┆ … ┆ 0    ┆ 0     ┆ 0     ┆ 231333 │
└─────┴──────┴─────┴──────┴───┴──────┴───────┴───────┴────────┘

En el caso de necesitar un resumen rápido y más completo, podemos hacer uso del método `describe`.

In [12]:
datos.describe()

shape: (9, 16)
┌─────────┬─────────┬─────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ statist ┆ id      ┆ name    ┆ sex    ┆ … ┆ city   ┆ sport  ┆ event  ┆ medal  │
│ ic      ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ ---     ┆ f64     ┆ str     ┆ str    ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
│ str     ┆         ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
╞═════════╪═════════╪═════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ count   ┆ 271116. ┆ 271116  ┆ 271116 ┆ … ┆ 271116 ┆ 271116 ┆ 271116 ┆ 39783  │
│         ┆ 0       ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ null_co ┆ 0.0     ┆ 0       ┆ 0      ┆ … ┆ 0      ┆ 0      ┆ 0      ┆ 231333 │
│ unt     ┆         ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ mean    ┆ 68248.9 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 54396   ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ std     ┆ 39022.2 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 86345   ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ min     ┆ 1.0     ┆ A       ┆ F      ┆ … ┆ Albert ┆ Aerona ┆ Aerona ┆ Bronze │
│         ┆         ┆ Dijiang ┆        ┆   ┆ ville  ┆ utics  ┆ utics  ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Mixed  ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Aerona ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ utics  ┆        │
│ 25%     ┆ 34643.0 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│ 50%     ┆ 68205.0 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│ 75%     ┆ 102097. ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 0       ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ max     ┆ 135571. ┆ zzet    ┆ M      ┆ … ┆ Vancou ┆ Wrestl ┆ Wrestl ┆ Silver │
│         ┆ 0       ┆ nce     ┆        ┆   ┆ ver    ┆ ing    ┆ ing    ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Women' ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ s Midd ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ leweig ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ ht…    ┆        │
└─────────┴─────────┴─────────┴────────┴───┴────────┴────────┴────────┴────────┘

Si se quieren descartar rápidamente filas con valores nulos en algunas de sus columnas, se usa el método `drop_nulls`.

In [13]:
datos.drop_nulls()

shape: (30_181, 15)
┌────────┬───────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬────────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city     ┆ sport    ┆ event    ┆ medal  │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---    │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str      ┆ str      ┆ str      ┆ str    │
╞════════╪═══════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪════════╡
│ 16     ┆ Juhamatti ┆ M   ┆ 28  ┆ … ┆ Sochi    ┆ Ice      ┆ Ice      ┆ Bronze │
│        ┆ Tapio     ┆     ┆     ┆   ┆          ┆ Hockey   ┆ Hockey   ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Ice      ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Hockey   ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Bronze │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Individu ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ al Al…   ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Team All ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ -Arou…   ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Horse    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Vault    ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Pommelle ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ d Hor…   ┆        │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …        ┆ …        ┆ …        ┆ …      │
│ 135553 ┆ Galina    ┆ F   ┆ 25  ┆ … ┆ Melbourn ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Ivanovna  ┆     ┆     ┆   ┆ e        ┆ s        ┆ s        ┆        │
│        ┆ Zybina    ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ (-Fyodo…  ┆     ┆     ┆   ┆          ┆          ┆ Shot Put ┆        │
│ 135553 ┆ Galina    ┆ F   ┆ 33  ┆ … ┆ Tokyo    ┆ Athletic ┆ Athletic ┆ Bronze │
│        ┆ Ivanovna  ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ Zybina    ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ (-Fyodo…  ┆     ┆     ┆   ┆          ┆          ┆ Shot Put ┆        │
│ 135554 ┆ Bogusaw   ┆ M   ┆ 28  ┆ … ┆ Moskva   ┆ Fencing  ┆ Fencing  ┆ Bronze │
│        ┆ Zych      ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Foil,    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Team     ┆        │
│ 135563 ┆ Olesya    ┆ F   ┆ 19  ┆ … ┆ Sydney   ┆ Athletic ┆ Athletic ┆ Bronze │
│        ┆ Nikolayev ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ na Zykina ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 400  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
│ 135563 ┆ Olesya    ┆ F   ┆ 23  ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Nikolayev ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ na Zykina ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 400  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
└────────┴───────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴────────┘

Vale la pena notar que los `DataFrame` también cuentan con el método `drop_nans`, pero este descarta filas con valores numéricos que no son válidos.

## Cálculo de resumenes

A la hora de trabajar con datos, suele ser de interés procesarlos de alguna manera para obtener información respecto de algunas variables relevantes. 
Por ejemplo, se pueden calcular valores medios, mínimos, máximos, medianas, diferencias, razones, etc. 
Las cuentas que resumen muchos datos en un único valor se llaman resumenes o agregaciones (porque se están resumiendo agregando varios valores de alguna forma en un único valor).

### Resumenes simples

Como ya vimos, una forma muy rápida de calcular estadísticas básicas con un `DataFrame` es utilizar el método `.describe`, que genera estadísticas básicas para las columnas numéricas del conjunto de datos. Veamos que también nos permite especificar el listado de percentiles que queremos utilizar.

In [14]:
datos.describe(percentiles=[0.1, 0.4, 0.6, 0.9])

shape: (10, 16)
┌─────────┬─────────┬─────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ statist ┆ id      ┆ name    ┆ sex    ┆ … ┆ city   ┆ sport  ┆ event  ┆ medal  │
│ ic      ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ ---     ┆ f64     ┆ str     ┆ str    ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
│ str     ┆         ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
╞═════════╪═════════╪═════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ count   ┆ 271116. ┆ 271116  ┆ 271116 ┆ … ┆ 271116 ┆ 271116 ┆ 271116 ┆ 39783  │
│         ┆ 0       ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ null_co ┆ 0.0     ┆ 0       ┆ 0      ┆ … ┆ 0      ┆ 0      ┆ 0      ┆ 231333 │
│ unt     ┆         ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ mean    ┆ 68248.9 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 54396   ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ std     ┆ 39022.2 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 86345   ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ min     ┆ 1.0     ┆ A       ┆ F      ┆ … ┆ Albert ┆ Aerona ┆ Aerona ┆ Bronze │
│         ┆         ┆ Dijiang ┆        ┆   ┆ ville  ┆ utics  ┆ utics  ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Mixed  ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Aerona ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ utics  ┆        │
│ 10%     ┆ 14102.0 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│ 40%     ┆ 54826.0 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│ 60%     ┆ 81686.0 ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│ 90%     ┆ 122194. ┆ null    ┆ null   ┆ … ┆ null   ┆ null   ┆ null   ┆ null   │
│         ┆ 0       ┆         ┆        ┆   ┆        ┆        ┆        ┆        │
│ max     ┆ 135571. ┆ zzet    ┆ M      ┆ … ┆ Vancou ┆ Wrestl ┆ Wrestl ┆ Silver │
│         ┆ 0       ┆ nce     ┆        ┆   ┆ ver    ┆ ing    ┆ ing    ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ Women' ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ s Midd ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ leweig ┆        │
│         ┆         ┆         ┆        ┆   ┆        ┆        ┆ ht…    ┆        │
└─────────┴─────────┴─────────┴────────┴───┴────────┴────────┴────────┴────────┘

A nivel columna, si queremos calcular la cantidad de ocurrencias de una columna categórica o discreta, podemos seleccionar la columna y luego usar `value_counts()`.

In [15]:
datos["sex"].value_counts()

shape: (2, 2)
┌─────┬────────┐
│ sex ┆ count  │
│ --- ┆ ---    │
│ str ┆ u32    │
╞═════╪════════╡
│ F   ┆ 74522  │
│ M   ┆ 196594 │
└─────┴────────┘

Notemos que el método `value_counts` pertenece a la `Series` y no al `DataFrame`.

In [16]:
type(datos["sex"])

polars.series.series.Series

Este método también recibe los parámetros `sort` que ordena las filas de mayor a menor cantidad de ocurrencias, `name` que permite renombrar la columna de conteo y `normalize` que divide los conteos por su suma de modo tal que representan una proporción.

In [17]:
datos["noc"].value_counts(sort=True)

shape: (230, 2)
┌─────┬───────┐
│ noc ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ USA ┆ 18853 │
│ FRA ┆ 12758 │
│ GBR ┆ 12256 │
│ ITA ┆ 10715 │
│ GER ┆ 9830  │
│ …   ┆ …     │
│ YMD ┆ 5     │
│ SSD ┆ 3     │
│ NBO ┆ 2     │
│ UNK ┆ 2     │
│ NFL ┆ 1     │
└─────┴───────┘

In [18]:
datos["noc"].value_counts(sort=True, name="n")

shape: (230, 2)
┌─────┬───────┐
│ noc ┆ n     │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ USA ┆ 18853 │
│ FRA ┆ 12758 │
│ GBR ┆ 12256 │
│ ITA ┆ 10715 │
│ GER ┆ 9830  │
│ …   ┆ …     │
│ YMD ┆ 5     │
│ SSD ┆ 3     │
│ NBO ┆ 2     │
│ UNK ┆ 2     │
│ NFL ┆ 1     │
└─────┴───────┘

In [19]:
datos["noc"].value_counts(sort=True, name="p", normalize=True)

shape: (230, 2)
┌─────┬──────────┐
│ noc ┆ p        │
│ --- ┆ ---      │
│ str ┆ f64      │
╞═════╪══════════╡
│ USA ┆ 0.069539 │
│ FRA ┆ 0.047057 │
│ GBR ┆ 0.045206 │
│ ITA ┆ 0.039522 │
│ GER ┆ 0.036258 │
│ …   ┆ …        │
│ YMD ┆ 0.000018 │
│ SSD ┆ 0.000011 │
│ NBO ┆ 0.000007 │
│ UNK ┆ 0.000007 │
│ NFL ┆ 0.000004 │
└─────┴──────────┘

Otros métodos interesantes son `unique` y `.n_unique`, que devuelven los valores únicos de una columna y su cantidad.

In [20]:
datos["noc"].unique()

shape: (230,)
Series: 'noc' [str]
[
	"TLS"
	"GUM"
	"PAK"
	"NOR"
	"GBS"
	…
	"KAZ"
	"MDV"
	"SAM"
	"STP"
	"VIN"
]

In [21]:
datos["noc"].n_unique()

230

In [22]:
datos["games"].unique()

shape: (51,)
Series: 'games' [str]
[
	"1988 Winter"
	"1980 Winter"
	"1980 Summer"
	"2014 Winter"
	"1976 Winter"
	…
	"1984 Winter"
	"1924 Summer"
	"1896 Summer"
	"1998 Winter"
	"1932 Summer"
]

En cuanto a las variables numéricas, las `Series` de Polars ofrecen una gran variedad de resumenes estadísticos:

In [23]:
datos["age"].mean()

25.556898357297374

In [24]:
print("Media:", datos["age"].mean())
print("Mediana:", datos["age"].median())
print("Desvío estándar:", datos["age"].std())
print("Mínimo:", datos["age"].min())
print("Máximo:", datos["age"].max())
print("Percentil 10:", datos["age"].quantile(0.1))

Media: 25.556898357297374
Mediana: 24.0
Desvío estándar: 6.393560847035814
Mínimo: 10
Máximo: 97
Percentil 10: 19.0

### Expresiones

En Polars, es posible construir expresiones que representan transformaciones sobre los datos.

Para hacerlo, primero se indican las columnas con `pl.col()` y luego se las combina usando operadores aritméticos habituales o métodos provistos por Polars.

Por ejemplo, la siguiente expresión combina las columnas `"height"` y `"weight"` de modo tal que se calcule el índice de masa corporal.

In [25]:
pl.col("weight") / (pl.col("height") / 100) ** 2

Como se puede ver, el bloque anterior todavía no realiza ningún cálculo sobre el conjunto de datos. Lo que hace es definir, de forma abstracta, una transformación que queremos aplicar.

Para evaluar esa expresión, en este caso para calcular el índice de masa corporal, necesitamos usarla dentro de un contexto de ejecución. Polars ofrece varios, pero por ahora nos interesa `select`. Este contexto permite aplicar expresiones sobre las columnas y producir nuevas columnas, ya sea como resúmenes, combinaciones de columnas existentes o incluso valores literales.

Veamos que, en principio, `select` permite seleccionar columnas:

In [26]:
datos.select("name", "age", "sex")

shape: (271_116, 3)
┌──────────────────────────┬─────┬─────┐
│ name                     ┆ age ┆ sex │
│ ---                      ┆ --- ┆ --- │
│ str                      ┆ i64 ┆ str │
╞══════════════════════════╪═════╪═════╡
│ A Dijiang                ┆ 24  ┆ M   │
│ A Lamusi                 ┆ 23  ┆ M   │
│ Gunnar Nielsen Aaby      ┆ 24  ┆ M   │
│ Edgar Lindenau Aabye     ┆ 34  ┆ M   │
│ Christine Jacoba Aaftink ┆ 21  ┆ F   │
│ …                        ┆ …   ┆ …   │
│ Andrzej ya               ┆ 29  ┆ M   │
│ Piotr ya                 ┆ 27  ┆ M   │
│ Piotr ya                 ┆ 27  ┆ M   │
│ Tomasz Ireneusz ya       ┆ 30  ┆ M   │
│ Tomasz Ireneusz ya       ┆ 34  ┆ M   │
└──────────────────────────┴─────┴─────┘

Sin embargo, como acabamos de mencionar, también permite ejecutar expresiones.

In [27]:
datos.select("name", pl.col("age") * 12)

shape: (271_116, 2)
┌──────────────────────────┬─────┐
│ name                     ┆ age │
│ ---                      ┆ --- │
│ str                      ┆ i64 │
╞══════════════════════════╪═════╡
│ A Dijiang                ┆ 288 │
│ A Lamusi                 ┆ 276 │
│ Gunnar Nielsen Aaby      ┆ 288 │
│ Edgar Lindenau Aabye     ┆ 408 │
│ Christine Jacoba Aaftink ┆ 252 │
│ …                        ┆ …   │
│ Andrzej ya               ┆ 348 │
│ Piotr ya                 ┆ 324 │
│ Piotr ya                 ┆ 324 │
│ Tomasz Ireneusz ya       ┆ 360 │
│ Tomasz Ireneusz ya       ┆ 408 │
└──────────────────────────┴─────┘

Si queremos guardar el resultado de la expresión en una nueva columna, tenemos que pasarla como parámetro:

In [28]:
datos.select(
    "name", 
    "height", 
    "weight", 
    bmi=pl.col("weight") / (pl.col("height") / 100) ** 2
)

shape: (271_116, 4)
┌──────────────────────────┬────────┬────────┬───────────┐
│ name                     ┆ height ┆ weight ┆ bmi       │
│ ---                      ┆ ---    ┆ ---    ┆ ---       │
│ str                      ┆ i64    ┆ f64    ┆ f64       │
╞══════════════════════════╪════════╪════════╪═══════════╡
│ A Dijiang                ┆ 180    ┆ 80.0   ┆ 24.691358 │
│ A Lamusi                 ┆ 170    ┆ 60.0   ┆ 20.761246 │
│ Gunnar Nielsen Aaby      ┆ null   ┆ null   ┆ null      │
│ Edgar Lindenau Aabye     ┆ null   ┆ null   ┆ null      │
│ Christine Jacoba Aaftink ┆ 185    ┆ 82.0   ┆ 23.959094 │
│ …                        ┆ …      ┆ …      ┆ …         │
│ Andrzej ya               ┆ 179    ┆ 89.0   ┆ 27.776911 │
│ Piotr ya                 ┆ 176    ┆ 59.0   ┆ 19.047004 │
│ Piotr ya                 ┆ 176    ┆ 59.0   ┆ 19.047004 │
│ Tomasz Ireneusz ya       ┆ 185    ┆ 96.0   ┆ 28.049671 │
│ Tomasz Ireneusz ya       ┆ 185    ┆ 96.0   ┆ 28.049671 │
└──────────────────────────┴────────┴────────┴───────────┘

O utilizar el método `alias`.

In [29]:
datos.select(
    "name", 
    "height", 
    "weight", 
    (pl.col("weight") / (pl.col("height") / 100) ** 2).alias("bmi")
)

shape: (271_116, 4)
┌──────────────────────────┬────────┬────────┬───────────┐
│ name                     ┆ height ┆ weight ┆ bmi       │
│ ---                      ┆ ---    ┆ ---    ┆ ---       │
│ str                      ┆ i64    ┆ f64    ┆ f64       │
╞══════════════════════════╪════════╪════════╪═══════════╡
│ A Dijiang                ┆ 180    ┆ 80.0   ┆ 24.691358 │
│ A Lamusi                 ┆ 170    ┆ 60.0   ┆ 20.761246 │
│ Gunnar Nielsen Aaby      ┆ null   ┆ null   ┆ null      │
│ Edgar Lindenau Aabye     ┆ null   ┆ null   ┆ null      │
│ Christine Jacoba Aaftink ┆ 185    ┆ 82.0   ┆ 23.959094 │
│ …                        ┆ …      ┆ …      ┆ …         │
│ Andrzej ya               ┆ 179    ┆ 89.0   ┆ 27.776911 │
│ Piotr ya                 ┆ 176    ┆ 59.0   ┆ 19.047004 │
│ Piotr ya                 ┆ 176    ┆ 59.0   ┆ 19.047004 │
│ Tomasz Ireneusz ya       ┆ 185    ┆ 96.0   ┆ 28.049671 │
│ Tomasz Ireneusz ya       ┆ 185    ┆ 96.0   ┆ 28.049671 │
└──────────────────────────┴────────┴────────┴───────────┘

Retemando el cálculo de resumenes, es posible utilizar un método de agregación, por ejempĺo:

In [30]:
datos.select(pl.col("age").mean())

shape: (1, 1)
┌───────────┐
│ age       │
│ ---       │
│ f64       │
╞═══════════╡
│ 25.556898 │
└───────────┘

In [31]:
datos.select(
    pl.col("age").mean().alias("edad_promedio"),
    pl.col("height").mean().alias("altura_promedio"),
)

shape: (1, 2)
┌───────────────┬─────────────────┐
│ edad_promedio ┆ altura_promedio │
│ ---           ┆ ---             │
│ f64           ┆ f64             │
╞═══════════════╪═════════════════╡
│ 25.556898     ┆ 175.33897       │
└───────────────┴─────────────────┘

O bien:

In [32]:
datos.select(
    pl.col("age").mean().alias("edad_media"),
    pl.col("age").std().alias("edad_std"),
)

shape: (1, 2)
┌────────────┬──────────┐
│ edad_media ┆ edad_std │
│ ---        ┆ ---      │
│ f64        ┆ f64      │
╞════════════╪══════════╡
│ 25.556898  ┆ 6.393561 │
└────────────┴──────────┘

Como iremos viendo a lo largo del curso, las expresiones de Polars son muy potentes y se pueden usar en varios contextos, no solo en `select`.

### Resumenes agrupados

El siguiente paso es calcular resumenes para cada nivel de otra variable (o combinaciones de niveles de múltiples variables).

Por ejemplo:

* ¿Cuál es la edad promedio de los atletas en cada juego olímpico?
* ¿Cuántas medallas de oro ganó cada país en cada edición?
* ¿Qué país estuvo más represenado por mujeres?

Lo primero que tenemos que conocer para realizar esta tarea es método `group_by`, que es un contexto de ejecución de expresiones.

Este método agrupa el `DataFrame` según una o más columnas para que luego podamos aplicar agregaciones sobre cada grupo.

In [33]:
datos.group_by("year")

La representación del objeto agrupado es bastante austera, pero una vez agrupados los datos podemos aplicar agregaciones con `.agg()`.

In [34]:
datos.group_by("games").agg(pl.col("age").mean())

shape: (51, 2)
┌─────────────┬───────────┐
│ games       ┆ age       │
│ ---         ┆ ---       │
│ str         ┆ f64       │
╞═════════════╪═══════════╡
│ 1906 Summer ┆ 27.125253 │
│ 1984 Summer ┆ 24.002811 │
│ 1928 Winter ┆ 26.581301 │
│ 1976 Winter ┆ 23.739459 │
│ 1924 Summer ┆ 28.449373 │
│ …           ┆ …         │
│ 1956 Summer ┆ 26.033673 │
│ 1952 Summer ┆ 26.258851 │
│ 1980 Winter ┆ 23.65616  │
│ 1932 Summer ┆ 33.45154  │
│ 1960 Winter ┆ 24.241877 │
└─────────────┴───────────┘

Utilizando el método `sort()` se puede obtener una tabla ordenada según variables de interés, por ejemplo `games`.

In [35]:
datos.group_by("games").agg(pl.col("age").mean()).sort("games")

shape: (51, 2)
┌─────────────┬───────────┐
│ games       ┆ age       │
│ ---         ┆ ---       │
│ str         ┆ f64       │
╞═════════════╪═══════════╡
│ 1896 Summer ┆ 23.580645 │
│ 1900 Summer ┆ 29.034031 │
│ 1904 Summer ┆ 26.69815  │
│ 1906 Summer ┆ 27.125253 │
│ 1908 Summer ┆ 26.970228 │
│ …           ┆ …         │
│ 2008 Summer ┆ 25.734118 │
│ 2010 Winter ┆ 26.124262 │
│ 2012 Summer ┆ 25.961378 │
│ 2014 Winter ┆ 25.987324 │
│ 2016 Summer ┆ 26.207919 │
└─────────────┴───────────┘

Y con un poco de creatividad podemos obtener la edición donde se presentó el atleta mas longevo:

In [36]:
datos.group_by("games").agg(pl.col("age").max()).sort("age").tail(1)

shape: (1, 2)
┌─────────────┬─────┐
│ games       ┆ age │
│ ---         ┆ --- │
│ str         ┆ i64 │
╞═════════════╪═════╡
│ 1928 Summer ┆ 97  │
└─────────────┴─────┘

Otro ejemplo:

In [37]:
(
    datos
    .group_by("games", "noc")
    .agg(
        (pl.col("sex") == "F").mean().alias("p_mujer"),
        pl.len().alias("n")
    )
    .sort("p_mujer", "n")
    .tail(10)
)

shape: (10, 4)
┌─────────────┬─────┬─────────┬─────┐
│ games       ┆ noc ┆ p_mujer ┆ n   │
│ ---         ┆ --- ┆ ---     ┆ --- │
│ str         ┆ str ┆ f64     ┆ u32 │
╞═════════════╪═════╪═════════╪═════╡
│ 2014 Winter ┆ TOG ┆ 1.0     ┆ 3   │
│ 1992 Winter ┆ HON ┆ 1.0     ┆ 3   │
│ 2006 Winter ┆ HKG ┆ 1.0     ┆ 3   │
│ 1988 Summer ┆ MYA ┆ 1.0     ┆ 3   │
│ 2006 Winter ┆ DEN ┆ 1.0     ┆ 4   │
│ 1932 Winter ┆ GBR ┆ 1.0     ┆ 4   │
│ 2002 Winter ┆ HKG ┆ 1.0     ┆ 5   │
│ 1960 Summer ┆ ZIM ┆ 1.0     ┆ 10  │
│ 1972 Winter ┆ PRK ┆ 1.0     ┆ 10  │
│ 1976 Summer ┆ PER ┆ 1.0     ┆ 14  │
└─────────────┴─────┴─────────┴─────┘

Una forma de obtener la cantidad de observaciones por grupo es:

In [38]:
datos.group_by("games", "noc").agg(pl.len())

shape: (3_837, 3)
┌─────────────┬─────┬─────┐
│ games       ┆ noc ┆ len │
│ ---         ┆ --- ┆ --- │
│ str         ┆ str ┆ u32 │
╞═════════════╪═════╪═════╡
│ 1988 Summer ┆ ASA ┆ 6   │
│ 1956 Summer ┆ PHI ┆ 48  │
│ 1960 Summer ┆ HAI ┆ 1   │
│ 2002 Winter ┆ EST ┆ 51  │
│ 2016 Summer ┆ SEN ┆ 22  │
│ …           ┆ …   ┆ …   │
│ 1988 Summer ┆ ANG ┆ 33  │
│ 1984 Summer ┆ FRA ┆ 354 │
│ 1996 Summer ┆ BOL ┆ 9   │
│ 2010 Winter ┆ SLO ┆ 107 │
│ 1900 Summer ┆ GRE ┆ 4   │
└─────────────┴─────┴─────┘

## Manipulación de columnas

### Seleccionar y transformar

Podemos seleccionar una columna de un `DataFrame` pasando el nombre de la misma dentro de corchetes (de la misma forma que haríamos con un diccionario).

In [39]:
datos["noc"]

shape: (271_116,)
Series: 'noc' [str]
[
	"CHN"
	"CHN"
	"DEN"
	"DEN"
	"NED"
	…
	"POL"
	"POL"
	"POL"
	"POL"
	"POL"
]

El resultado es una `Series`, no un `DataFrame` compuesto por una sola columna.

In [40]:
type(datos["noc"])

polars.series.series.Series

Si queremos obtener un `DataFrame`, tenemos que usar el método `select`.

In [41]:
datos.select("noc")

shape: (271_116, 1)
┌─────┐
│ noc │
│ --- │
│ str │
╞═════╡
│ CHN │
│ CHN │
│ DEN │
│ DEN │
│ NED │
│ …   │
│ POL │
│ POL │
│ POL │
│ POL │
│ POL │
└─────┘

In [42]:
type(datos.select("noc"))

polars.dataframe.frame.DataFrame

In [43]:
datos.select(pl.col("noc").alias("pais"))

shape: (271_116, 1)
┌──────┐
│ pais │
│ ---  │
│ str  │
╞══════╡
│ CHN  │
│ CHN  │
│ DEN  │
│ DEN  │
│ NED  │
│ …    │
│ POL  │
│ POL  │
│ POL  │
│ POL  │
│ POL  │
└──────┘

In [44]:
datos.select(pl.col("noc").alias("pais"), pl.col("age").mean())

shape: (271_116, 2)
┌──────┬───────────┐
│ pais ┆ age       │
│ ---  ┆ ---       │
│ str  ┆ f64       │
╞══════╪═══════════╡
│ CHN  ┆ 25.556898 │
│ CHN  ┆ 25.556898 │
│ DEN  ┆ 25.556898 │
│ DEN  ┆ 25.556898 │
│ NED  ┆ 25.556898 │
│ …    ┆ …         │
│ POL  ┆ 25.556898 │
│ POL  ┆ 25.556898 │
│ POL  ┆ 25.556898 │
│ POL  ┆ 25.556898 │
│ POL  ┆ 25.556898 │
└──────┴───────────┘

In [45]:
datos.select((pl.col("weight") - pl.col("weight").mean()) / pl.col("weight").std())

shape: (271_116, 1)
┌───────────┐
│ weight    │
│ ---       │
│ f64       │
╞═══════════╡
│ 0.648006  │
│ -0.745914 │
│ null      │
│ null      │
│ 0.787398  │
│ …         │
│ 1.275271  │
│ -0.81561  │
│ -0.81561  │
│ 1.763143  │
│ 1.763143  │
└───────────┘

Si se desea modificar y/o agregar columnas a un `DataFrame`, conviene utilizar el contexto `with_columns`, que devuelve una tabla con todas las columnas del `DataFrame` original junto con las nuevas columnas generadas a partir de las expresiones.

In [46]:
datos.with_columns(
    weight_z=(pl.col("weight") - pl.col("weight").mean()) / pl.col("weight").std()
)

shape: (271_116, 16)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬───────┬──────────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ sport     ┆ event    ┆ medal ┆ weight_z │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---   ┆ ---      │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str   ┆ f64      │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪═══════╪══════════╡
│ 1      ┆ A Dijiang ┆ M   ┆ 24  ┆ … ┆ Basketbal ┆ Basketba ┆ null  ┆ 0.648006 │
│        ┆           ┆     ┆     ┆   ┆ l         ┆ ll Men's ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Basketba ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ ll       ┆       ┆          │
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ Judo      ┆ Judo     ┆ null  ┆ -0.74591 │
│        ┆           ┆     ┆     ┆   ┆           ┆ Men's    ┆       ┆ 4        │
│        ┆           ┆     ┆     ┆   ┆           ┆ Extra-Li ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ ghtweigh ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ t        ┆       ┆          │
│ 3      ┆ Gunnar    ┆ M   ┆ 24  ┆ … ┆ Football  ┆ Football ┆ null  ┆ null     │
│        ┆ Nielsen   ┆     ┆     ┆   ┆           ┆ Men's    ┆       ┆          │
│        ┆ Aaby      ┆     ┆     ┆   ┆           ┆ Football ┆       ┆          │
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Tug-Of-Wa ┆ Tug-Of-W ┆ Gold  ┆ null     │
│        ┆ Lindenau  ┆     ┆     ┆   ┆ r         ┆ ar Men's ┆       ┆          │
│        ┆ Aabye     ┆     ┆     ┆   ┆           ┆ Tug-Of-W ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ ar       ┆       ┆          │
│ 5      ┆ Christine ┆ F   ┆ 21  ┆ … ┆ Speed     ┆ Speed    ┆ null  ┆ 0.787398 │
│        ┆ Jacoba    ┆     ┆     ┆   ┆ Skating   ┆ Skating  ┆       ┆          │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆ Women's  ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ 500      ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ metr…    ┆       ┆          │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …     ┆ …        │
│ 135569 ┆ Andrzej   ┆ M   ┆ 29  ┆ … ┆ Luge      ┆ Luge     ┆ null  ┆ 1.275271 │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆ Mixed    ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ (Men)'s  ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Doubles  ┆       ┆          │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Ski       ┆ Ski      ┆ null  ┆ -0.81561 │
│        ┆           ┆     ┆     ┆   ┆ Jumping   ┆ Jumping  ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Men's    ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Large    ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Hill, …  ┆       ┆          │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Ski       ┆ Ski      ┆ null  ┆ -0.81561 │
│        ┆           ┆     ┆     ┆   ┆ Jumping   ┆ Jumping  ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Men's    ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Large    ┆       ┆          │
│        ┆           ┆     ┆     ┆   ┆           ┆ Hill, …  ┆       ┆          │
│ 135571 ┆ Tomasz    ┆ M   ┆ 30  ┆ … ┆ Bobsleigh ┆ Bobsleig ┆ null  ┆ 1.763143 │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h Men's  ┆       ┆          │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆ Four     ┆       ┆          │
│ 135571 ┆ Tomasz    ┆ M   ┆ 34  ┆ … ┆ Bobsleigh ┆ Bobsleig ┆ null  ┆ 1.763143 │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h Men's  ┆       ┆          │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆ Four     ┆       ┆          │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴───────┴──────────┘

Debido a esta diferencia entre `select` y with_co`lumns, las expresiones usadas dentro de `with_columns` deben producir series que tengan la misma longitud que las columnas originales del `DataFrame`. 
En cambio, en el contexto `select` alcanza con que las expresiones produzcan series de la misma longitud entre sí.

### Descartar

Para descartar columnas tenemos el método `.drop`. Simplemente le pasamos el nombre de las columnas que queremos descartar.

In [47]:
datos.drop("id", "year", "season")

shape: (271_116, 12)
┌───────────┬─────┬─────┬────────┬───┬───────────┬──────────┬──────────┬───────┐
│ name      ┆ sex ┆ age ┆ height ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---       ┆ --- ┆ --- ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ str       ┆ str ┆ i64 ┆ i64    ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞═══════════╪═════╪═════╪════════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ A Dijiang ┆ M   ┆ 24  ┆ 180    ┆ … ┆ Barcelona ┆ Basketba ┆ Basketba ┆ null  │
│           ┆     ┆     ┆        ┆   ┆           ┆ ll       ┆ ll Men's ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Basketba ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ ll       ┆       │
│ A Lamusi  ┆ M   ┆ 23  ┆ 170    ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Men's    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Extra-Li ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ ghtweigh ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ t        ┆       │
│ Gunnar    ┆ M   ┆ 24  ┆ null   ┆ … ┆ Antwerpen ┆ Football ┆ Football ┆ null  │
│ Nielsen   ┆     ┆     ┆        ┆   ┆           ┆          ┆ Men's    ┆       │
│ Aaby      ┆     ┆     ┆        ┆   ┆           ┆          ┆ Football ┆       │
│ Edgar     ┆ M   ┆ 34  ┆ null   ┆ … ┆ Paris     ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold  │
│ Lindenau  ┆     ┆     ┆        ┆   ┆           ┆ ar       ┆ ar Men's ┆       │
│ Aabye     ┆     ┆     ┆        ┆   ┆           ┆          ┆ Tug-Of-W ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ ar       ┆       │
│ Christine ┆ F   ┆ 21  ┆ 185    ┆ … ┆ Calgary   ┆ Speed    ┆ Speed    ┆ null  │
│ Jacoba    ┆     ┆     ┆        ┆   ┆           ┆ Skating  ┆ Skating  ┆       │
│ Aaftink   ┆     ┆     ┆        ┆   ┆           ┆          ┆ Women's  ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ 500      ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ metr…    ┆       │
│ …         ┆ …   ┆ …   ┆ …      ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ Andrzej   ┆ M   ┆ 29  ┆ 179    ┆ … ┆ Innsbruck ┆ Luge     ┆ Luge     ┆ null  │
│ ya        ┆     ┆     ┆        ┆   ┆           ┆          ┆ Mixed    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ (Men)'s  ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Doubles  ┆       │
│ Piotr ya  ┆ M   ┆ 27  ┆ 176    ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│           ┆     ┆     ┆        ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Men's    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Large    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ Piotr ya  ┆ M   ┆ 27  ┆ 176    ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│           ┆     ┆     ┆        ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Men's    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Large    ┆       │
│           ┆     ┆     ┆        ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ Tomasz    ┆ M   ┆ 30  ┆ 185    ┆ … ┆ Nagano    ┆ Bobsleig ┆ Bobsleig ┆ null  │
│ Ireneusz  ┆     ┆     ┆        ┆   ┆           ┆ h        ┆ h Men's  ┆       │
│ ya        ┆     ┆     ┆        ┆   ┆           ┆          ┆ Four     ┆       │
│ Tomasz    ┆ M   ┆ 34  ┆ 185    ┆ … ┆ Salt Lake ┆ Bobsleig ┆ Bobsleig ┆ null  │
│ Ireneusz  ┆     ┆     ┆        ┆   ┆ City      ┆ h        ┆ h Men's  ┆       │
│ ya        ┆     ┆     ┆        ┆   ┆           ┆          ┆ Four     ┆       │
└───────────┴─────┴─────┴────────┴───┴───────────┴──────────┴──────────┴───────┘

### Renombrar

In [48]:
datos.select("name", "sex", "age").rename({"name": "nombre", "sex": "sexo", "age": "edad"})

shape: (271_116, 3)
┌──────────────────────────┬──────┬──────┐
│ nombre                   ┆ sexo ┆ edad │
│ ---                      ┆ ---  ┆ ---  │
│ str                      ┆ str  ┆ i64  │
╞══════════════════════════╪══════╪══════╡
│ A Dijiang                ┆ M    ┆ 24   │
│ A Lamusi                 ┆ M    ┆ 23   │
│ Gunnar Nielsen Aaby      ┆ M    ┆ 24   │
│ Edgar Lindenau Aabye     ┆ M    ┆ 34   │
│ Christine Jacoba Aaftink ┆ F    ┆ 21   │
│ …                        ┆ …    ┆ …    │
│ Andrzej ya               ┆ M    ┆ 29   │
│ Piotr ya                 ┆ M    ┆ 27   │
│ Piotr ya                 ┆ M    ┆ 27   │
│ Tomasz Ireneusz ya       ┆ M    ┆ 30   │
│ Tomasz Ireneusz ya       ┆ M    ┆ 34   │
└──────────────────────────┴──────┴──────┘

## Manipulación de filas

### Ordenar

Para ordenar las observaciones en función de una o más variables usamos `.sort()`. Si pasamos una sola columna alcanza con una cadena; si queremos ordenar por varias, conviene pasar una lista.

El argumento `descending` permite invertir el orden. Como Polars no usa un índice persistente, ordenar las filas no requiere ningún paso extra para reenumerarlas.

In [49]:
datos.sort("year")

shape: (271_116, 15)
┌────────┬───────────┬─────┬──────┬───┬──────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age  ┆ … ┆ city     ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64  ┆   ┆ str      ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪══════╪═══╪══════════╪══════════╪══════════╪═══════╡
│ 1724   ┆ Aristidis ┆ M   ┆ null ┆ … ┆ Athina   ┆ Tennis   ┆ Tennis   ┆ null  │
│        ┆ Akratopou ┆     ┆      ┆   ┆          ┆          ┆ Men's    ┆       │
│        ┆ los       ┆     ┆      ┆   ┆          ┆          ┆ Singles  ┆       │
│ 1724   ┆ Aristidis ┆ M   ┆ null ┆ … ┆ Athina   ┆ Tennis   ┆ Tennis   ┆ null  │
│        ┆ Akratopou ┆     ┆      ┆   ┆          ┆          ┆ Men's    ┆       │
│        ┆ los       ┆     ┆      ┆   ┆          ┆          ┆ Doubles  ┆       │
│ 1725   ┆ Konstanti ┆ M   ┆ null ┆ … ┆ Athina   ┆ Tennis   ┆ Tennis   ┆ null  │
│        ┆ nos       ┆     ┆      ┆   ┆          ┆          ┆ Men's    ┆       │
│        ┆ "Kostas"  ┆     ┆      ┆   ┆          ┆          ┆ Singles  ┆       │
│        ┆ Akratopo… ┆     ┆      ┆   ┆          ┆          ┆          ┆       │
│ 1725   ┆ Konstanti ┆ M   ┆ null ┆ … ┆ Athina   ┆ Tennis   ┆ Tennis   ┆ null  │
│        ┆ nos       ┆     ┆      ┆   ┆          ┆          ┆ Men's    ┆       │
│        ┆ "Kostas"  ┆     ┆      ┆   ┆          ┆          ┆ Doubles  ┆       │
│        ┆ Akratopo… ┆     ┆      ┆   ┆          ┆          ┆          ┆       │
│ 4113   ┆ Anastasio ┆ M   ┆ null ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ s Andreou ┆     ┆      ┆   ┆          ┆ s        ┆ s Men's  ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ 110      ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ metres   ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ Hur…     ┆       │
│ …      ┆ …         ┆ …   ┆ …    ┆ … ┆ …        ┆ …        ┆ …        ┆ …     │
│ 135528 ┆ Marc      ┆ M   ┆ 32   ┆ … ┆ Rio de   ┆ Badminto ┆ Badminto ┆ null  │
│        ┆ Zwiebler  ┆     ┆      ┆   ┆ Janeiro  ┆ n        ┆ n Men's  ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ Singles  ┆       │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23   ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ Viktorovn ┆     ┆      ┆   ┆ Janeiro  ┆ s        ┆ s        ┆       │
│        ┆ a         ┆     ┆      ┆   ┆          ┆          ┆ Women's  ┆       │
│        ┆ Zyabkina  ┆     ┆      ┆   ┆          ┆          ┆ 100      ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ metres   ┆       │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23   ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ Viktorovn ┆     ┆      ┆   ┆ Janeiro  ┆ s        ┆ s        ┆       │
│        ┆ a         ┆     ┆      ┆   ┆          ┆          ┆ Women's  ┆       │
│        ┆ Zyabkina  ┆     ┆      ┆   ┆          ┆          ┆ 200      ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ metres   ┆       │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23   ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ Viktorovn ┆     ┆      ┆   ┆ Janeiro  ┆ s        ┆ s        ┆       │
│        ┆ a         ┆     ┆      ┆   ┆          ┆          ┆ Women's  ┆       │
│        ┆ Zyabkina  ┆     ┆      ┆   ┆          ┆          ┆ 4 x 100  ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ metr…    ┆       │
│ 135568 ┆ Olga      ┆ F   ┆ 33   ┆ … ┆ Rio de   ┆ Basketba ┆ Basketba ┆ null  │
│        ┆ Igorevna  ┆     ┆      ┆   ┆ Janeiro  ┆ ll       ┆ ll       ┆       │
│        ┆ Zyuzkova  ┆     ┆      ┆   ┆          ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆      ┆   ┆          ┆          ┆ ll       ┆       │
└────────┴───────────┴─────┴──────┴───┴──────────┴──────────┴──────────┴───────┘

In [50]:
datos.sort("year", descending=True)

shape: (271_116, 15)
┌────────┬──────────┬─────┬──────┬───┬──────────┬──────────┬──────────┬────────┐
│ id     ┆ name     ┆ sex ┆ age  ┆ … ┆ city     ┆ sport    ┆ event    ┆ medal  │
│ ---    ┆ ---      ┆ --- ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---    │
│ i64    ┆ str      ┆ str ┆ i64  ┆   ┆ str      ┆ str      ┆ str      ┆ str    │
╞════════╪══════════╪═════╪══════╪═══╪══════════╪══════════╪══════════╪════════╡
│ 22     ┆ Andreea  ┆ F   ┆ 22   ┆ … ┆ Rio de   ┆ Weightli ┆ Weightli ┆ null   │
│        ┆ Aanei    ┆     ┆      ┆   ┆ Janeiro  ┆ fting    ┆ fting    ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Super-He ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ …        ┆        │
│ 51     ┆ Nstor    ┆ M   ┆ 23   ┆ … ┆ Rio de   ┆ Gymnasti ┆ Gymnasti ┆ null   │
│        ┆ Abad     ┆     ┆      ┆   ┆ Janeiro  ┆ cs       ┆ cs Men's ┆        │
│        ┆ Sanjun   ┆     ┆      ┆   ┆          ┆          ┆ Individu ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ al Al…   ┆        │
│ 51     ┆ Nstor    ┆ M   ┆ 23   ┆ … ┆ Rio de   ┆ Gymnasti ┆ Gymnasti ┆ null   │
│        ┆ Abad     ┆     ┆      ┆   ┆ Janeiro  ┆ cs       ┆ cs Men's ┆        │
│        ┆ Sanjun   ┆     ┆      ┆   ┆          ┆          ┆ Floor    ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Exercis… ┆        │
│ 51     ┆ Nstor    ┆ M   ┆ 23   ┆ … ┆ Rio de   ┆ Gymnasti ┆ Gymnasti ┆ null   │
│        ┆ Abad     ┆     ┆      ┆   ┆ Janeiro  ┆ cs       ┆ cs Men's ┆        │
│        ┆ Sanjun   ┆     ┆      ┆   ┆          ┆          ┆ Parallel ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Bars     ┆        │
│ 51     ┆ Nstor    ┆ M   ┆ 23   ┆ … ┆ Rio de   ┆ Gymnasti ┆ Gymnasti ┆ null   │
│        ┆ Abad     ┆     ┆      ┆   ┆ Janeiro  ┆ cs       ┆ cs Men's ┆        │
│        ┆ Sanjun   ┆     ┆      ┆   ┆          ┆          ┆ Horizont ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ al Ba…   ┆        │
│ …      ┆ …        ┆ …   ┆ …    ┆ … ┆ …        ┆ …        ┆ …        ┆ …      │
│ 135285 ┆ Khristos ┆ M   ┆ null ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Zoumis   ┆     ┆      ┆   ┆          ┆ s        ┆ s Men's  ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Triple   ┆        │
│        ┆          ┆     ┆      ┆   ┆          ┆          ┆ Jump     ┆        │
│ 135481 ┆ Jules    ┆ M   ┆ 30   ┆ … ┆ Athina   ┆ Gymnasti ┆ Gymnasti ┆ Silver │
│        ┆ Alexis   ┆     ┆      ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ "Louis"  ┆     ┆      ┆   ┆          ┆          ┆ Horse    ┆        │
│        ┆ Zutter   ┆     ┆      ┆   ┆          ┆          ┆ Vault    ┆        │
│ 135481 ┆ Jules    ┆ M   ┆ 30   ┆ … ┆ Athina   ┆ Gymnasti ┆ Gymnasti ┆ Silver │
│        ┆ Alexis   ┆     ┆      ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ "Louis"  ┆     ┆      ┆   ┆          ┆          ┆ Parallel ┆        │
│        ┆ Zutter   ┆     ┆      ┆   ┆          ┆          ┆ Bars     ┆        │
│ 135481 ┆ Jules    ┆ M   ┆ 30   ┆ … ┆ Athina   ┆ Gymnasti ┆ Gymnasti ┆ null   │
│        ┆ Alexis   ┆     ┆      ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ "Louis"  ┆     ┆      ┆   ┆          ┆          ┆ Horizont ┆        │
│        ┆ Zutter   ┆     ┆      ┆   ┆          ┆          ┆ al Ba…   ┆        │
│ 135481 ┆ Jules    ┆ M   ┆ 30   ┆ … ┆ Athina   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Alexis   ┆     ┆      ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ "Louis"  ┆     ┆      ┆   ┆          ┆          ┆ Pommelle ┆        │
│        ┆ Zutter   ┆     ┆      ┆   ┆          ┆          ┆ d Hor…   ┆        │
└────────┴──────────┴─────┴──────┴───┴──────────┴──────────┴──────────┴────────┘

In [51]:
datos.sort(["season", "year"])

shape: (271_116, 15)
┌────────┬───────────┬─────┬──────┬───┬────────┬───────────┬──────────┬────────┐
│ id     ┆ name      ┆ sex ┆ age  ┆ … ┆ city   ┆ sport     ┆ event    ┆ medal  │
│ ---    ┆ ---       ┆ --- ┆ ---  ┆   ┆ ---    ┆ ---       ┆ ---      ┆ ---    │
│ i64    ┆ str       ┆ str ┆ i64  ┆   ┆ str    ┆ str       ┆ str      ┆ str    │
╞════════╪═══════════╪═════╪══════╪═══╪════════╪═══════════╪══════════╪════════╡
│ 57440  ┆ Karakatsa ┆ M   ┆ null ┆ … ┆ Athina ┆ Shooting  ┆ Shooting ┆ null   │
│        ┆ nis       ┆     ┆      ┆   ┆        ┆           ┆ Men's    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Free     ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Rifle,   ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Thr…     ┆        │
│ 122329 ┆ Georgios  ┆ M   ┆ null ┆ … ┆ Athina ┆ Wrestling ┆ Wrestlin ┆ Silver │
│        ┆ Tsitas    ┆     ┆      ┆   ┆        ┆           ┆ g Men's  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Unlimite ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ d Clas…  ┆        │
│ 122303 ┆ Leonidas  ┆ M   ┆ null ┆ … ┆ Athina ┆ Gymnastic ┆ Gymnasti ┆ null   │
│        ┆ Tsiklitir ┆     ┆      ┆   ┆        ┆ s         ┆ cs Men's ┆        │
│        ┆ as        ┆     ┆      ┆   ┆        ┆           ┆ Horizont ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ al Ba…   ┆        │
│ 38123  ┆ Carl      ┆ M   ┆ 23   ┆ … ┆ Athina ┆ Athletics ┆ Athletic ┆ null   │
│        ┆ Galle     ┆     ┆      ┆   ┆        ┆           ┆ s Men's  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ 1,500    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ metres   ┆        │
│ 122152 ┆ A. Tryfia ┆ M   ┆ null ┆ … ┆ Athina ┆ Cycling   ┆ Cycling  ┆ null   │
│        ┆ tis-Trypi ┆     ┆      ┆   ┆        ┆           ┆ Men's    ┆        │
│        ┆ apis      ┆     ┆      ┆   ┆        ┆           ┆ 12-Hours ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Race     ┆        │
│ …      ┆ …         ┆ …   ┆ …    ┆ … ┆ …      ┆ …         ┆ …        ┆ …      │
│ 23464  ┆ Charle    ┆ M   ┆ 22   ┆ … ┆ Sochi  ┆ Short     ┆ Short    ┆ null   │
│        ┆ Cournoyer ┆     ┆      ┆   ┆        ┆ Track     ┆ Track    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆ Speed     ┆ Speed    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆ Skating   ┆ Skating  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Men'…    ┆        │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27   ┆ … ┆ Sochi  ┆ Ski       ┆ Ski      ┆ null   │
│        ┆           ┆     ┆      ┆   ┆        ┆ Jumping   ┆ Jumping  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Men's    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Large    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Hill, …  ┆        │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27   ┆ … ┆ Sochi  ┆ Ski       ┆ Ski      ┆ null   │
│        ┆           ┆     ┆      ┆   ┆        ┆ Jumping   ┆ Jumping  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Men's    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Large    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Hill, …  ┆        │
│ 31342  ┆ Tiril Kam ┆ F   ┆ 23   ┆ … ┆ Sochi  ┆ Biathlon  ┆ Biathlon ┆ Gold   │
│        ┆ penhaug   ┆     ┆      ┆   ┆        ┆           ┆ Mixed 2  ┆        │
│        ┆ Eckhoff   ┆     ┆      ┆   ┆        ┆           ┆ x 6 kilo ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ metre…   ┆        │
│ 128915 ┆ Yuta      ┆ M   ┆ 31   ┆ … ┆ Sochi  ┆ Ski       ┆ Ski      ┆ null   │
│        ┆ Watase    ┆     ┆      ┆   ┆        ┆ Jumping   ┆ Jumping  ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Men's    ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Normal   ┆        │
│        ┆           ┆     ┆      ┆   ┆        ┆           ┆ Hill,…   ┆        │
└────────┴───────────┴─────┴──────┴───┴────────┴───────────┴──────────┴────────┘

### Filtrar

Es posible seleccionar filas por posición usando _slices_.  Esto resulta útil para inspeccionar rápidamente una parte de la tabla.

In [52]:
datos[0:10]

shape: (10, 15)
┌─────┬────────────┬─────┬─────┬───┬───────────┬───────────┬───────────┬───────┐
│ id  ┆ name       ┆ sex ┆ age ┆ … ┆ city      ┆ sport     ┆ event     ┆ medal │
│ --- ┆ ---        ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---   │
│ i64 ┆ str        ┆ str ┆ i64 ┆   ┆ str       ┆ str       ┆ str       ┆ str   │
╞═════╪════════════╪═════╪═════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 1   ┆ A Dijiang  ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketbal ┆ Basketbal ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆ l         ┆ l Men's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Basketbal ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ l         ┆       │
│ 2   ┆ A Lamusi   ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo      ┆ Judo      ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Men's Ext ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ ra-Lightw ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ eight     ┆       │
│ 3   ┆ Gunnar     ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football  ┆ Football  ┆ null  │
│     ┆ Nielsen    ┆     ┆     ┆   ┆           ┆           ┆ Men's     ┆       │
│     ┆ Aaby       ┆     ┆     ┆   ┆           ┆           ┆ Football  ┆       │
│ 4   ┆ Edgar      ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-Wa ┆ Tug-Of-Wa ┆ Gold  │
│     ┆ Lindenau   ┆     ┆     ┆   ┆           ┆ r         ┆ r Men's   ┆       │
│     ┆ Aabye      ┆     ┆     ┆   ┆           ┆           ┆ Tug-Of-Wa ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ r         ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 1,000 me… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ le        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ le        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 1,000 me… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 27  ┆ … ┆ Lillehamm ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ er        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 27  ┆ … ┆ Lillehamm ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ er        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 1,000 me… ┆       │
└─────┴────────────┴─────┴─────┴───┴───────────┴───────────┴───────────┴───────┘

In [53]:
datos[0:10:2]

shape: (5, 15)
┌─────┬────────────┬─────┬─────┬───┬───────────┬───────────┬───────────┬───────┐
│ id  ┆ name       ┆ sex ┆ age ┆ … ┆ city      ┆ sport     ┆ event     ┆ medal │
│ --- ┆ ---        ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---   │
│ i64 ┆ str        ┆ str ┆ i64 ┆   ┆ str       ┆ str       ┆ str       ┆ str   │
╞═════╪════════════╪═════╪═════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 1   ┆ A Dijiang  ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketbal ┆ Basketbal ┆ null  │
│     ┆            ┆     ┆     ┆   ┆           ┆ l         ┆ l Men's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ Basketbal ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ l         ┆       │
│ 3   ┆ Gunnar     ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football  ┆ Football  ┆ null  │
│     ┆ Nielsen    ┆     ┆     ┆   ┆           ┆           ┆ Men's     ┆       │
│     ┆ Aaby       ┆     ┆     ┆   ┆           ┆           ┆ Football  ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆           ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ le        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
│ 5   ┆ Christine  ┆ F   ┆ 27  ┆ … ┆ Lillehamm ┆ Speed     ┆ Speed     ┆ null  │
│     ┆ Jacoba     ┆     ┆     ┆   ┆ er        ┆ Skating   ┆ Skating   ┆       │
│     ┆ Aaftink    ┆     ┆     ┆   ┆           ┆           ┆ Women's   ┆       │
│     ┆            ┆     ┆     ┆   ┆           ┆           ┆ 500 metr… ┆       │
└─────┴────────────┴─────┴─────┴───┴───────────┴───────────┴───────────┴───────┘

In [54]:
datos[0:100:10, :5]

shape: (10, 5)
┌─────┬──────────────────────────┬─────┬─────┬────────┐
│ id  ┆ name                     ┆ sex ┆ age ┆ height │
│ --- ┆ ---                      ┆ --- ┆ --- ┆ ---    │
│ i64 ┆ str                      ┆ str ┆ i64 ┆ i64    │
╞═════╪══════════════════════════╪═════╪═════╪════════╡
│ 1   ┆ A Dijiang                ┆ M   ┆ 24  ┆ 180    │
│ 6   ┆ Per Knut Aaland          ┆ M   ┆ 31  ┆ 188    │
│ 7   ┆ John Aalberg             ┆ M   ┆ 31  ┆ 183    │
│ 11  ┆ Jorma Ilmari Aalto       ┆ M   ┆ 22  ┆ 182    │
│ 16  ┆ Juhamatti Tapio Aaltonen ┆ M   ┆ 28  ┆ 184    │
│ 17  ┆ Paavo Johannes Aaltonen  ┆ M   ┆ 32  ┆ 175    │
│ 20  ┆ Kjetil Andr Aamodt       ┆ M   ┆ 20  ┆ 176    │
│ 20  ┆ Kjetil Andr Aamodt       ┆ M   ┆ 26  ┆ 176    │
│ 22  ┆ Andreea Aanei            ┆ F   ┆ 22  ┆ 170    │
│ 28  ┆ Jan-Erik Aarberg         ┆ M   ┆ 47  ┆ 170    │
└─────┴──────────────────────────┴─────┴─────┴────────┘

Cuando lo que queremos es conservar filas según una condición sobre sus valores, en cambio, conviene usar el método `filter`.
Este método acepta condiciones en forma de expresiones booleanas, es decir, `filter` también es un contexto.

Por ejemplo, podemos quedarnos solo con los Juegos Olímpicos de invierno, excluirlos o combinar condiciones sobre `season`, `year`, `sport` o `medal`.

In [55]:
datos.filter(pl.col("season") == "Winter")

shape: (48_564, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 5      ┆ Christine ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆           ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 500      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ 5      ┆ Christine ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆           ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 1,000    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ me…      ┆       │
│ 5      ┆ Christine ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆ le        ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 500      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ 5      ┆ Christine ┆ F   ┆ 25  ┆ … ┆ Albertvil ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆ le        ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 1,000    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ me…      ┆       │
│ 5      ┆ Christine ┆ F   ┆ 27  ┆ … ┆ Lillehamm ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆ er        ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 500      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135569 ┆ Andrzej   ┆ M   ┆ 29  ┆ … ┆ Innsbruck ┆ Luge     ┆ Luge     ┆ null  │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Mixed    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ (Men)'s  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Doubles  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 30  ┆ … ┆ Nagano    ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 34  ┆ … ┆ Salt Lake ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆ City      ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

In [56]:
datos.filter(pl.col("season") != "Winter")

shape: (222_552, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 1      ┆ A Dijiang ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketba ┆ Basketba ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ ll       ┆ ll Men's ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Extra-Li ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ghtweigh ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ t        ┆       │
│ 3      ┆ Gunnar    ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football ┆ Football ┆ null  │
│        ┆ Nielsen   ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ Aaby      ┆     ┆     ┆   ┆           ┆          ┆ Football ┆       │
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold  │
│        ┆ Lindenau  ┆     ┆     ┆   ┆           ┆ ar       ┆ ar Men's ┆       │
│        ┆ Aabye     ┆     ┆     ┆   ┆           ┆          ┆ Tug-Of-W ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ar       ┆       │
│ 8      ┆ Cornelia  ┆ F   ┆ 18  ┆ … ┆ Los       ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ "Cor"     ┆     ┆     ┆   ┆ Angeles   ┆ s        ┆ s        ┆       │
│        ┆ Aalten    ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆ (-Strann… ┆     ┆     ┆   ┆           ┆          ┆ 100      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metres   ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135565 ┆ Fernando  ┆ M   ┆ 27  ┆ … ┆ Athina    ┆ Hockey   ┆ Hockey   ┆ null  │
│        ┆ scar Zylb ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ erberg    ┆     ┆     ┆   ┆           ┆          ┆ Hockey   ┆       │
│ 135566 ┆ James     ┆ M   ┆ 21  ┆ … ┆ Munich    ┆ Football ┆ Football ┆ null  │
│        ┆ Francis   ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ "Jim"     ┆     ┆     ┆   ┆           ┆          ┆ Football ┆       │
│        ┆ Zylker    ┆     ┆     ┆   ┆           ┆          ┆          ┆       │
│ 135567 ┆ Aleksandr ┆ M   ┆ 24  ┆ … ┆ Sydney    ┆ Rowing   ┆ Rowing   ┆ null  │
│        ┆ Viktorovi ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ ch Zyuzin ┆     ┆     ┆   ┆           ┆          ┆ Lightwei ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ght      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Coxle…   ┆       │
│ 135567 ┆ Aleksandr ┆ M   ┆ 28  ┆ … ┆ Athina    ┆ Rowing   ┆ Rowing   ┆ null  │
│        ┆ Viktorovi ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ ch Zyuzin ┆     ┆     ┆   ┆           ┆          ┆ Lightwei ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ght      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Coxle…   ┆       │
│ 135568 ┆ Olga      ┆ F   ┆ 33  ┆ … ┆ Rio de    ┆ Basketba ┆ Basketba ┆ null  │
│        ┆ Igorevna  ┆     ┆     ┆   ┆ Janeiro   ┆ ll       ┆ ll       ┆       │
│        ┆ Zyuzkova  ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

In [57]:
datos.filter(pl.col("season") == "Summer", pl.col("year") >= 2000)

shape: (67_474, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Extra-Li ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ghtweigh ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ t        ┆       │
│ 12     ┆ Jyri      ┆ M   ┆ 31  ┆ … ┆ Sydney    ┆ Badminto ┆ Badminto ┆ null  │
│        ┆ Tapani    ┆     ┆     ┆   ┆           ┆ n        ┆ n Men's  ┆       │
│        ┆ Aalto     ┆     ┆     ┆   ┆           ┆          ┆ Singles  ┆       │
│ 13     ┆ Minna     ┆ F   ┆ 34  ┆ … ┆ Sydney    ┆ Sailing  ┆ Sailing  ┆ null  │
│        ┆ Maarit    ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆ Aalto     ┆     ┆     ┆   ┆           ┆          ┆ Windsurf ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ er       ┆       │
│ 18     ┆ Timo      ┆ M   ┆ 31  ┆ … ┆ Sydney    ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ Antero    ┆     ┆     ┆   ┆           ┆ s        ┆ s Men's  ┆       │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆           ┆          ┆ Shot Put ┆       │
│ 21     ┆ Ragnhild  ┆ F   ┆ 27  ┆ … ┆ Beijing   ┆ Handball ┆ Handball ┆ Gold  │
│        ┆ Margrethe ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆ Aamodt    ┆     ┆     ┆   ┆           ┆          ┆ Handball ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135565 ┆ Fernando  ┆ M   ┆ 23  ┆ … ┆ Sydney    ┆ Hockey   ┆ Hockey   ┆ null  │
│        ┆ scar Zylb ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ erberg    ┆     ┆     ┆   ┆           ┆          ┆ Hockey   ┆       │
│ 135565 ┆ Fernando  ┆ M   ┆ 27  ┆ … ┆ Athina    ┆ Hockey   ┆ Hockey   ┆ null  │
│        ┆ scar Zylb ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ erberg    ┆     ┆     ┆   ┆           ┆          ┆ Hockey   ┆       │
│ 135567 ┆ Aleksandr ┆ M   ┆ 24  ┆ … ┆ Sydney    ┆ Rowing   ┆ Rowing   ┆ null  │
│        ┆ Viktorovi ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ ch Zyuzin ┆     ┆     ┆   ┆           ┆          ┆ Lightwei ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ght      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Coxle…   ┆       │
│ 135567 ┆ Aleksandr ┆ M   ┆ 28  ┆ … ┆ Athina    ┆ Rowing   ┆ Rowing   ┆ null  │
│        ┆ Viktorovi ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ ch Zyuzin ┆     ┆     ┆   ┆           ┆          ┆ Lightwei ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ght      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Coxle…   ┆       │
│ 135568 ┆ Olga      ┆ F   ┆ 33  ┆ … ┆ Rio de    ┆ Basketba ┆ Basketba ┆ null  │
│        ┆ Igorevna  ┆     ┆     ┆   ┆ Janeiro   ┆ ll       ┆ ll       ┆       │
│        ┆ Zyuzkova  ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

In [58]:
datos.filter(pl.col("medal").is_in(["Gold", "Silver"]))

shape: (26_488, 15)
┌────────┬───────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬────────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city     ┆ sport    ┆ event    ┆ medal  │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---    │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str      ┆ str      ┆ str      ┆ str    │
╞════════╪═══════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪════════╡
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Paris    ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold   │
│        ┆ Lindenau  ┆     ┆     ┆   ┆          ┆ ar       ┆ ar Men's ┆        │
│        ┆ Aabye     ┆     ┆     ┆   ┆          ┆          ┆ Tug-Of-W ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ ar       ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Team All ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ -Arou…   ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Horse    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Vault    ┆        │
│ 17     ┆ Paavo     ┆ M   ┆ 28  ┆ … ┆ London   ┆ Gymnasti ┆ Gymnasti ┆ Gold   │
│        ┆ Johannes  ┆     ┆     ┆   ┆          ┆ cs       ┆ cs Men's ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Pommelle ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ d Hor…   ┆        │
│ 20     ┆ Kjetil    ┆ M   ┆ 20  ┆ … ┆ Albertvi ┆ Alpine   ┆ Alpine   ┆ Gold   │
│        ┆ Andr      ┆     ┆     ┆   ┆ lle      ┆ Skiing   ┆ Skiing   ┆        │
│        ┆ Aamodt    ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Super G  ┆        │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …        ┆ …        ┆ …        ┆ …      │
│ 135544 ┆ Krzysztof ┆ M   ┆ 21  ┆ … ┆ Moskva   ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Zwoliski  ┆     ┆     ┆   ┆          ┆ s        ┆ s Men's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 100  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metres…  ┆        │
│ 135545 ┆ Henk Jan  ┆ M   ┆ 31  ┆ … ┆ Atlanta  ┆ Rowing   ┆ Rowing   ┆ Gold   │
│        ┆ Zwolle    ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Coxed    ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Eights   ┆        │
│ 135553 ┆ Galina    ┆ F   ┆ 21  ┆ … ┆ Helsinki ┆ Athletic ┆ Athletic ┆ Gold   │
│        ┆ Ivanovna  ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ Zybina    ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ (-Fyodo…  ┆     ┆     ┆   ┆          ┆          ┆ Shot Put ┆        │
│ 135553 ┆ Galina    ┆ F   ┆ 25  ┆ … ┆ Melbourn ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Ivanovna  ┆     ┆     ┆   ┆ e        ┆ s        ┆ s        ┆        │
│        ┆ Zybina    ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ (-Fyodo…  ┆     ┆     ┆   ┆          ┆          ┆ Shot Put ┆        │
│ 135563 ┆ Olesya    ┆ F   ┆ 23  ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Nikolayev ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ na Zykina ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 400  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
└────────┴───────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴────────┘

In [59]:
datos.filter(
    pl.col("sport").is_in(["Athletics", "Swimming"]),
    pl.col("year").is_between(2000, 2016)
)

shape: (19_887, 15)
┌────────┬───────────┬─────┬─────┬───┬──────────┬──────────┬──────────┬────────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city     ┆ sport    ┆ event    ┆ medal  │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---    │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str      ┆ str      ┆ str      ┆ str    │
╞════════╪═══════════╪═════╪═════╪═══╪══════════╪══════════╪══════════╪════════╡
│ 18     ┆ Timo      ┆ M   ┆ 31  ┆ … ┆ Sydney   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Antero    ┆     ┆     ┆   ┆          ┆ s        ┆ s Men's  ┆        │
│        ┆ Aaltonen  ┆     ┆     ┆   ┆          ┆          ┆ Shot Put ┆        │
│ 34     ┆ Jamale    ┆ M   ┆ 30  ┆ … ┆ London   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ (Djamel-) ┆     ┆     ┆   ┆          ┆ s        ┆ s Men's  ┆        │
│        ┆ Aarrass   ┆     ┆     ┆   ┆          ┆          ┆ 1,500    ┆        │
│        ┆ (Ahra…    ┆     ┆     ┆   ┆          ┆          ┆ metres   ┆        │
│ 36     ┆ Stefan    ┆ M   ┆ 25  ┆ … ┆ Sydney   ┆ Swimming ┆ Swimming ┆ null   │
│        ┆ Remco     ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆ Aartsen   ┆     ┆     ┆   ┆          ┆          ┆ 100      ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metres   ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Butt…    ┆        │
│ 36     ┆ Stefan    ┆ M   ┆ 25  ┆ … ┆ Sydney   ┆ Swimming ┆ Swimming ┆ null   │
│        ┆ Remco     ┆     ┆     ┆   ┆          ┆          ┆ Men's    ┆        │
│        ┆ Aartsen   ┆     ┆     ┆   ┆          ┆          ┆ 200      ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metres   ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Butt…    ┆        │
│ 49     ┆ Moonika   ┆ F   ┆ 24  ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Aava      ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Javelin  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ Thro…    ┆        │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …        ┆ …        ┆ …        ┆ …      │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23  ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Viktorovn ┆     ┆     ┆   ┆ Janeiro  ┆ s        ┆ s        ┆        │
│        ┆ a         ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ Zyabkina  ┆     ┆     ┆   ┆          ┆          ┆ 100      ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metres   ┆        │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23  ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Viktorovn ┆     ┆     ┆   ┆ Janeiro  ┆ s        ┆ s        ┆        │
│        ┆ a         ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ Zyabkina  ┆     ┆     ┆   ┆          ┆          ┆ 200      ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metres   ┆        │
│ 135547 ┆ Viktoriya ┆ F   ┆ 23  ┆ … ┆ Rio de   ┆ Athletic ┆ Athletic ┆ null   │
│        ┆ Viktorovn ┆     ┆     ┆   ┆ Janeiro  ┆ s        ┆ s        ┆        │
│        ┆ a         ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆ Zyabkina  ┆     ┆     ┆   ┆          ┆          ┆ 4 x 100  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
│ 135563 ┆ Olesya    ┆ F   ┆ 19  ┆ … ┆ Sydney   ┆ Athletic ┆ Athletic ┆ Bronze │
│        ┆ Nikolayev ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ na Zykina ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 400  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
│ 135563 ┆ Olesya    ┆ F   ┆ 23  ┆ … ┆ Athina   ┆ Athletic ┆ Athletic ┆ Silver │
│        ┆ Nikolayev ┆     ┆     ┆   ┆          ┆ s        ┆ s        ┆        │
│        ┆ na Zykina ┆     ┆     ┆   ┆          ┆          ┆ Women's  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ 4 x 400  ┆        │
│        ┆           ┆     ┆     ┆   ┆          ┆          ┆ metr…    ┆        │
└────────┴───────────┴─────┴─────┴───┴──────────┴──────────┴──────────┴────────┘

In [60]:
datos.filter((pl.col("year") < 1950) | (pl.col("year") > 2010))

shape: (77_751, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Extra-Li ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ghtweigh ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ t        ┆       │
│ 3      ┆ Gunnar    ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football ┆ Football ┆ null  │
│        ┆ Nielsen   ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ Aaby      ┆     ┆     ┆   ┆           ┆          ┆ Football ┆       │
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold  │
│        ┆ Lindenau  ┆     ┆     ┆   ┆           ┆ ar       ┆ ar Men's ┆       │
│        ┆ Aabye     ┆     ┆     ┆   ┆           ┆          ┆ Tug-Of-W ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ar       ┆       │
│ 8      ┆ Cornelia  ┆ F   ┆ 18  ┆ … ┆ Los       ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ "Cor"     ┆     ┆     ┆   ┆ Angeles   ┆ s        ┆ s        ┆       │
│        ┆ Aalten    ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆ (-Strann… ┆     ┆     ┆   ┆           ┆          ┆ 100      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metres   ┆       │
│ 8      ┆ Cornelia  ┆ F   ┆ 18  ┆ … ┆ Los       ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ "Cor"     ┆     ┆     ┆   ┆ Angeles   ┆ s        ┆ s        ┆       │
│        ┆ Aalten    ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆ (-Strann… ┆     ┆     ┆   ┆           ┆          ┆ 4 x 100  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135558 ┆ ukasz     ┆ M   ┆ 32  ┆ … ┆ London    ┆ Volleyba ┆ Volleyba ┆ null  │
│        ┆ Tomasz    ┆     ┆     ┆   ┆           ┆ ll       ┆ ll Men's ┆       │
│        ┆ ygado     ┆     ┆     ┆   ┆           ┆          ┆ Volleyba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
│ 135561 ┆ Frantiek  ┆ M   ┆ 26  ┆ … ┆ Amsterdam ┆ Athletic ┆ Athletic ┆ null  │
│        ┆ Zyka      ┆     ┆     ┆   ┆           ┆ s        ┆ s Men's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Marathon ┆       │
│ 135568 ┆ Olga      ┆ F   ┆ 33  ┆ … ┆ Rio de    ┆ Basketba ┆ Basketba ┆ null  │
│        ┆ Igorevna  ┆     ┆     ┆   ┆ Janeiro   ┆ ll       ┆ ll       ┆       │
│        ┆ Zyuzkova  ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

Cuando usamos operadores como `|` conviene encerrar cada comparación entre paréntesis para que la expresión se evalúe como esperamos.

### Descartar duplicados

En Polars podemos usar `.unique()` para quedarnos con combinaciones únicas de una o más columnas. Esto sirve tanto para explorar valores posibles como para descartar filas duplicadas según un subconjunto de variables.

Si usamos el parámetro `subset`, Polars decide si dos filas son duplicadas mirando solo esas columnas.

In [61]:
datos.select("season", "sport").unique()

shape: (69, 2)
┌────────┬────────────────┐
│ season ┆ sport          │
│ ---    ┆ ---            │
│ str    ┆ str            │
╞════════╪════════════════╡
│ Summer ┆ Croquet        │
│ Summer ┆ Gymnastics     │
│ Summer ┆ Lacrosse       │
│ Summer ┆ Diving         │
│ Winter ┆ Ice Hockey     │
│ …      ┆ …              │
│ Summer ┆ Roque          │
│ Summer ┆ Wrestling      │
│ Summer ┆ Badminton      │
│ Winter ┆ Alpinism       │
│ Summer ┆ Figure Skating │
└────────┴────────────────┘

In [62]:
datos.unique(subset=["season", "sport"])

shape: (69, 15)
┌──────┬───────────┬─────┬──────┬───┬───────────┬──────────┬──────────┬────────┐
│ id   ┆ name      ┆ sex ┆ age  ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal  │
│ ---  ┆ ---       ┆ --- ┆ ---  ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---    │
│ i64  ┆ str       ┆ str ┆ i64  ┆   ┆ str       ┆ str      ┆ str      ┆ str    │
╞══════╪═══════════╪═════╪══════╪═══╪═══════════╪══════════╪══════════╪════════╡
│ 23   ┆ Fritz     ┆ M   ┆ 22   ┆ … ┆ Sydney    ┆ Wrestlin ┆ Wrestlin ┆ null   │
│      ┆ Aanes     ┆     ┆      ┆   ┆           ┆ g        ┆ g Men's  ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Light-He ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ avywei…  ┆        │
│ 43   ┆ Morten    ┆ M   ┆ 34   ┆ … ┆ Barcelona ┆ Equestri ┆ Equestri ┆ null   │
│      ┆ Gjerdrum  ┆     ┆      ┆   ┆           ┆ anism    ┆ anism    ┆        │
│      ┆ Aasen     ┆     ┆      ┆   ┆           ┆          ┆ Mixed    ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Jumping, ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ I…       ┆        │
│ 154  ┆ Khadija   ┆ F   ┆ 40   ┆ … ┆ Beijing   ┆ Archery  ┆ Archery  ┆ null   │
│      ┆ Abbouda   ┆     ┆      ┆   ┆           ┆          ┆ Women's  ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Individu ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ al       ┆        │
│ 82   ┆ Enrique   ┆ M   ┆ 26   ┆ … ┆ Sydney    ┆ Tennis   ┆ Tennis   ┆ null   │
│      ┆ Abaroa    ┆     ┆      ┆   ┆           ┆          ┆ Men's    ┆        │
│      ┆ Martnez   ┆     ┆      ┆   ┆           ┆          ┆ Doubles  ┆        │
│ 8    ┆ Cornelia  ┆ F   ┆ 18   ┆ … ┆ Los       ┆ Athletic ┆ Athletic ┆ null   │
│      ┆ "Cor"     ┆     ┆      ┆   ┆ Angeles   ┆ s        ┆ s        ┆        │
│      ┆ Aalten    ┆     ┆      ┆   ┆           ┆          ┆ Women's  ┆        │
│      ┆ (-Strann… ┆     ┆      ┆   ┆           ┆          ┆ 100      ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ metres   ┆        │
│ …    ┆ …         ┆ …   ┆ …    ┆ … ┆ …         ┆ …        ┆ …        ┆ …      │
│ 5716 ┆ John      ┆ M   ┆ 21   ┆ … ┆ London    ┆ Racquets ┆ Racquets ┆ Bronze │
│      ┆ Jacob     ┆     ┆      ┆   ┆           ┆          ┆ Men's    ┆        │
│      ┆ Astor     ┆     ┆      ┆   ┆           ┆          ┆ Singles  ┆        │
│ 387  ┆ Sonia     ┆ F   ┆ 19   ┆ … ┆ Athina    ┆ Rhythmic ┆ Rhythmic ┆ null   │
│      ┆ Abejn     ┆     ┆      ┆   ┆           ┆ Gymnasti ┆ Gymnasti ┆        │
│      ┆ Esteban   ┆     ┆      ┆   ┆           ┆ cs       ┆ cs       ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Women's  ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Gr…      ┆        │
│ 20   ┆ Kjetil    ┆ M   ┆ 20   ┆ … ┆ Albertvil ┆ Alpine   ┆ Alpine   ┆ null   │
│      ┆ Andr      ┆     ┆      ┆   ┆ le        ┆ Skiing   ┆ Skiing   ┆        │
│      ┆ Aamodt    ┆     ┆      ┆   ┆           ┆          ┆ Men's    ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Downhill ┆        │
│ 21   ┆ Ragnhild  ┆ F   ┆ 27   ┆ … ┆ Beijing   ┆ Handball ┆ Handball ┆ Gold   │
│      ┆ Margrethe ┆     ┆      ┆   ┆           ┆          ┆ Women's  ┆        │
│      ┆ Aamodt    ┆     ┆      ┆   ┆           ┆          ┆ Handball ┆        │
│ 5822 ┆ George H. ┆ M   ┆ null ┆ … ┆ London    ┆ Motorboa ┆ Motorboa ┆ null   │
│      ┆ Atkinson  ┆     ┆      ┆   ┆           ┆ ting     ┆ ting     ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ Mixed    ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ A-Class  ┆        │
│      ┆           ┆     ┆      ┆   ┆           ┆          ┆ (Op…     ┆        │
└──────┴───────────┴─────┴──────┴───┴───────────┴──────────┴──────────┴────────┘

## Combinación de tablas

Para combinar tablas en Polars hay dos operaciones muy comunes: la **concatenación** y la **fusión**. La concatenación pega tablas por posición, mientras que la fusión relaciona filas a partir de una o más claves.

### Concatenación

La concatenación combina tablas que ya tienen una estructura compatible. Con `pl.concat()` podemos apilarlas verticalmente o pegarlas horizontalmente.

En una concatenación vertical, las filas de una tabla se agregan debajo de las de otra. En una concatenación horizontal, en cambio, las columnas se agregan lado a lado y las filas se alinean por posición.

In [63]:
ventas_2023 = pl.DataFrame({
    "id_venta": [1, 2, 3],
    "producto": ["Cuaderno", "Lapicera", "Regla"],
    "unidades": [5, 8, 3],
})

ventas_2024 = pl.DataFrame({
    "id_venta": [4, 5],
    "producto": ["Cuaderno", "Mochila"],
    "unidades": [6, 2],
})

detalle_ventas = pl.DataFrame({
    "id_venta": [1, 2, 3],
    "producto": ["Cuaderno", "Lapicera", "Regla"],
})

precios = pl.DataFrame({
    "precio_unitario": [1200, 800, 1500],
    "descuento": [0.10, 0.00, 0.05],
})

In [64]:
pl.concat([ventas_2023, ventas_2024], how="vertical")

shape: (5, 3)
┌──────────┬──────────┬──────────┐
│ id_venta ┆ producto ┆ unidades │
│ ---      ┆ ---      ┆ ---      │
│ i64      ┆ str      ┆ i64      │
╞══════════╪══════════╪══════════╡
│ 1        ┆ Cuaderno ┆ 5        │
│ 2        ┆ Lapicera ┆ 8        │
│ 3        ┆ Regla    ┆ 3        │
│ 4        ┆ Cuaderno ┆ 6        │
│ 5        ┆ Mochila  ┆ 2        │
└──────────┴──────────┴──────────┘

In [65]:
pl.concat([detalle_ventas, precios], how="horizontal")

shape: (3, 4)
┌──────────┬──────────┬─────────────────┬───────────┐
│ id_venta ┆ producto ┆ precio_unitario ┆ descuento │
│ ---      ┆ ---      ┆ ---             ┆ ---       │
│ i64      ┆ str      ┆ i64             ┆ f64       │
╞══════════╪══════════╪═════════════════╪═══════════╡
│ 1        ┆ Cuaderno ┆ 1200            ┆ 0.1       │
│ 2        ┆ Lapicera ┆ 800             ┆ 0.0       │
│ 3        ┆ Regla    ┆ 1500            ┆ 0.05      │
└──────────┴──────────┴─────────────────┴───────────┘

### Fusión

Cuando queremos combinar tablas a partir de una clave compartida, usamos `.join()`. Los tipos de fusión más comunes son `inner`, `left`, `right` y `full`.

* `inner`: conserva solo las filas con coincidencia en ambas tablas.
* `left`: conserva todas las filas de la tabla izquierda y agrega coincidencias de la derecha.
* `right`: conserva todas las filas de la tabla derecha y agrega coincidencias de la izquierda.
* `full`: conserva todas las filas de ambas tablas, aunque no tengan coincidencia.

La documentación oficial de Polars muestra más variantes y detalles sobre joins: https://docs.pola.rs/user-guide/transformations/joins/

In [66]:
clientes = pl.DataFrame({
    "id_cliente": [101, 102, 103, 105],
    "nombre": ["Ana", "Bruno", "Carla", "Diego"],
})

segmentos = pl.DataFrame({
    "id_cliente": [102, 103, 104],
    "segmento": ["Mayorista", "Minorista", "Mayorista"],
})

In [67]:
clientes.join(segmentos, on="id_cliente", how="inner")

shape: (2, 3)
┌────────────┬────────┬───────────┐
│ id_cliente ┆ nombre ┆ segmento  │
│ ---        ┆ ---    ┆ ---       │
│ i64        ┆ str    ┆ str       │
╞════════════╪════════╪═══════════╡
│ 102        ┆ Bruno  ┆ Mayorista │
│ 103        ┆ Carla  ┆ Minorista │
└────────────┴────────┴───────────┘

In [68]:
clientes.join(segmentos, on="id_cliente")

shape: (2, 3)
┌────────────┬────────┬───────────┐
│ id_cliente ┆ nombre ┆ segmento  │
│ ---        ┆ ---    ┆ ---       │
│ i64        ┆ str    ┆ str       │
╞════════════╪════════╪═══════════╡
│ 102        ┆ Bruno  ┆ Mayorista │
│ 103        ┆ Carla  ┆ Minorista │
└────────────┴────────┴───────────┘

El resultado es el mismo porque `how` es por defecto igual a `"inner"`.

In [69]:
clientes.join(segmentos, on="id_cliente", how="left")

shape: (4, 3)
┌────────────┬────────┬───────────┐
│ id_cliente ┆ nombre ┆ segmento  │
│ ---        ┆ ---    ┆ ---       │
│ i64        ┆ str    ┆ str       │
╞════════════╪════════╪═══════════╡
│ 101        ┆ Ana    ┆ null      │
│ 102        ┆ Bruno  ┆ Mayorista │
│ 103        ┆ Carla  ┆ Minorista │
│ 105        ┆ Diego  ┆ null      │
└────────────┴────────┴───────────┘

In [70]:
clientes.join(segmentos, on="id_cliente", how="right")

shape: (3, 3)
┌────────┬────────────┬───────────┐
│ nombre ┆ id_cliente ┆ segmento  │
│ ---    ┆ ---        ┆ ---       │
│ str    ┆ i64        ┆ str       │
╞════════╪════════════╪═══════════╡
│ Bruno  ┆ 102        ┆ Mayorista │
│ Carla  ┆ 103        ┆ Minorista │
│ null   ┆ 104        ┆ Mayorista │
└────────┴────────────┴───────────┘

In [71]:
clientes.join(segmentos, on="id_cliente", how="full")

shape: (5, 4)
┌────────────┬────────┬──────────────────┬───────────┐
│ id_cliente ┆ nombre ┆ id_cliente_right ┆ segmento  │
│ ---        ┆ ---    ┆ ---              ┆ ---       │
│ i64        ┆ str    ┆ i64              ┆ str       │
╞════════════╪════════╪══════════════════╪═══════════╡
│ 101        ┆ Ana    ┆ null             ┆ null      │
│ 102        ┆ Bruno  ┆ 102              ┆ Mayorista │
│ 103        ┆ Carla  ┆ 103              ┆ Minorista │
│ 105        ┆ Diego  ┆ null             ┆ null      │
│ null       ┆ null   ┆ 104              ┆ Mayorista │
└────────────┴────────┴──────────────────┴───────────┘

También es posible unir usando más de una columna. En ese caso, le pasamos a `on` una lista con los nombres de las claves que deben coincidir simultáneamente.

In [72]:
ventas_sucursal = pl.DataFrame({
    "sucursal": ["Centro", "Centro", "Norte", "Norte"],
    "producto": ["Cuaderno", "Lapicera", "Cuaderno", "Mochila"],
    "unidades": [20, 35, 18, 7],
})

precios_sucursal = pl.DataFrame({
    "sucursal": ["Centro", "Centro", "Norte", "Sur"],
    "producto": ["Cuaderno", "Lapicera", "Cuaderno", "Mochila"],
    "precio_unitario": [1200, 800, 1250, 32000],
})

ventas_sucursal.join(precios_sucursal, on=["sucursal", "producto"], how="left")

shape: (4, 4)
┌──────────┬──────────┬──────────┬─────────────────┐
│ sucursal ┆ producto ┆ unidades ┆ precio_unitario │
│ ---      ┆ ---      ┆ ---      ┆ ---             │
│ str      ┆ str      ┆ i64      ┆ i64             │
╞══════════╪══════════╪══════════╪═════════════════╡
│ Centro   ┆ Cuaderno ┆ 20       ┆ 1200            │
│ Centro   ┆ Lapicera ┆ 35       ┆ 800             │
│ Norte    ┆ Cuaderno ┆ 18       ┆ 1250            │
│ Norte    ┆ Mochila  ┆ 7        ┆ null            │
└──────────┴──────────┴──────────┴─────────────────┘

## Escritura de de datos

Así como Polars ofrece varias funciones para leer datos, también incluye métodos para exportarlos. Uno de los más usados es `.write_csv`, aunque también existen `.write_parquet` y `.write_excel` (estos últimos pueden requerir dependencias adicionales).

El primer argumento de `.write_csv` es la ruta donde queremos guardar el archivo.

In [73]:
datos.head(10).write_csv("primeras_10_filas.csv")

In [74]:
datos

shape: (271_116, 15)
┌────────┬───────────┬─────┬─────┬───┬───────────┬──────────┬──────────┬───────┐
│ id     ┆ name      ┆ sex ┆ age ┆ … ┆ city      ┆ sport    ┆ event    ┆ medal │
│ ---    ┆ ---       ┆ --- ┆ --- ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---   │
│ i64    ┆ str       ┆ str ┆ i64 ┆   ┆ str       ┆ str      ┆ str      ┆ str   │
╞════════╪═══════════╪═════╪═════╪═══╪═══════════╪══════════╪══════════╪═══════╡
│ 1      ┆ A Dijiang ┆ M   ┆ 24  ┆ … ┆ Barcelona ┆ Basketba ┆ Basketba ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ ll       ┆ ll Men's ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Basketba ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ll       ┆       │
│ 2      ┆ A Lamusi  ┆ M   ┆ 23  ┆ … ┆ London    ┆ Judo     ┆ Judo     ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Extra-Li ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ghtweigh ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ t        ┆       │
│ 3      ┆ Gunnar    ┆ M   ┆ 24  ┆ … ┆ Antwerpen ┆ Football ┆ Football ┆ null  │
│        ┆ Nielsen   ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆ Aaby      ┆     ┆     ┆   ┆           ┆          ┆ Football ┆       │
│ 4      ┆ Edgar     ┆ M   ┆ 34  ┆ … ┆ Paris     ┆ Tug-Of-W ┆ Tug-Of-W ┆ Gold  │
│        ┆ Lindenau  ┆     ┆     ┆   ┆           ┆ ar       ┆ ar Men's ┆       │
│        ┆ Aabye     ┆     ┆     ┆   ┆           ┆          ┆ Tug-Of-W ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ ar       ┆       │
│ 5      ┆ Christine ┆ F   ┆ 21  ┆ … ┆ Calgary   ┆ Speed    ┆ Speed    ┆ null  │
│        ┆ Jacoba    ┆     ┆     ┆   ┆           ┆ Skating  ┆ Skating  ┆       │
│        ┆ Aaftink   ┆     ┆     ┆   ┆           ┆          ┆ Women's  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ 500      ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ metr…    ┆       │
│ …      ┆ …         ┆ …   ┆ …   ┆ … ┆ …         ┆ …        ┆ …        ┆ …     │
│ 135569 ┆ Andrzej   ┆ M   ┆ 29  ┆ … ┆ Innsbruck ┆ Luge     ┆ Luge     ┆ null  │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Mixed    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ (Men)'s  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Doubles  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135570 ┆ Piotr ya  ┆ M   ┆ 27  ┆ … ┆ Sochi     ┆ Ski      ┆ Ski      ┆ null  │
│        ┆           ┆     ┆     ┆   ┆           ┆ Jumping  ┆ Jumping  ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Men's    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Large    ┆       │
│        ┆           ┆     ┆     ┆   ┆           ┆          ┆ Hill, …  ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 30  ┆ … ┆ Nagano    ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆           ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
│ 135571 ┆ Tomasz    ┆ M   ┆ 34  ┆ … ┆ Salt Lake ┆ Bobsleig ┆ Bobsleig ┆ null  │
│        ┆ Ireneusz  ┆     ┆     ┆   ┆ City      ┆ h        ┆ h Men's  ┆       │
│        ┆ ya        ┆     ┆     ┆   ┆           ┆          ┆ Four     ┆       │
└────────┴───────────┴─────┴─────┴───┴───────────┴──────────┴──────────┴───────┘

In [75]:
df_equipos = (
    datos
    .filter(pl.col("season") == "Summer")
    .group_by("year")
    .agg(pl.col("noc").n_unique())
    .sort("year")
)
df_equipos

shape: (29, 2)
┌──────┬─────┐
│ year ┆ noc │
│ ---  ┆ --- │
│ i64  ┆ u32 │
╞══════╪═════╡
│ 1896 ┆ 12  │
│ 1900 ┆ 31  │
│ 1904 ┆ 15  │
│ 1906 ┆ 21  │
│ 1908 ┆ 22  │
│ …    ┆ …   │
│ 2000 ┆ 200 │
│ 2004 ┆ 201 │
│ 2008 ┆ 204 │
│ 2012 ┆ 205 │
│ 2016 ┆ 207 │
└──────┴─────┘

In [76]:
df_equipos.write_csv("equipos_por_año.csv")

## Enlaces útiles

- [Python Polars: The Definitive Guide (Libro)](https://polarsguide.com/)
- [Guía oficial de Polars](https://docs.pola.rs/])
- [Polars Cheat Sheet](https://franzdiebold.github.io/polars-cheat-sheet/Polars_cheat_sheet.pdf)